// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ_iH-yQyLGjZUmrkIBAtp9FCgcyonzIU',
    appId: '1:238263170774:web:ee6128d4099994fc8a7b77',
    messagingSenderId: '238263170774',
    projectId: 'quiznep111',
    authDomain: 'quiznep111.firebaseapp.com',
    storageBucket: 'quiznep111.firebasestorage.app',
    measurementId: 'G-CVYSQ7KBKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCZDO-Fh5MorNRSDy4grOQuksgFhBtCH4',
    appId: '1:238263170774:android:21b226769f02bd1d8a7b77',
    messagingSenderId: '238263170774',
    projectId: 'quiznep111',
    storageBucket: 'quiznep111.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy1TmMgbxOP-x2uhN2Lm7OQ8e4TCrbfew',
    appId: '1:238263170774:ios:e7168f6b757350b48a7b77',
    messagingSenderId: '238263170774',
    projectId: 'quiznep111',
    storageBucket: 'quiznep111.firebasestorage.app',
    iosBundleId: 'com.example.quiznep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy1TmMgbxOP-x2uhN2Lm7OQ8e4TCrbfew',
    appId: '1:238263170774:ios:e7168f6b757350b48a7b77',
    messagingSenderId: '238263170774',
    projectId: 'quiznep111',
    storageBucket: 'quiznep111.firebasestorage.app',
    iosBundleId: 'com.example.quiznep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ_iH-yQyLGjZUmrkIBAtp9FCgcyonzIU',
    appId: '1:238263170774:web:d13bacdf0c8a8cb58a7b77',
    messagingSenderId: '238263170774',
    projectId: 'quiznep111',
    authDomain: 'quiznep111.firebaseapp.com',
    storageBucket: 'quiznep111.firebasestorage.app',
    measurementId: 'G-SS97W3SBZ9',
  );
}
